
services:
  db:
    image: postgres:latest
    # restart: always # Always restart the container if it stops
    environment:
      POSTGRES_USER: myuser # Sets the default user
      POSTGRES_PASSWORD: mysecretpassword # Sets the password for the user
      POSTGRES_DB: smartfood # Sets a default database name
    ports:
      - "5432:5432" # Maps port 5432 on your host to port 5432 in the container
    volumes:
      - postgres_data:/var/lib/postgresql # Persist data to a named volume

volumes:
  postgres_data: